### ISSUE TITLE
Qt slot function should be made in separate thread

### ISSUE THREAD

**Issue by yijiangh** [yijiangh/choreo#27]
Ref to [this post](https://groups.google.com/forum/#!topic/swri-ros-pkg-dev/nKf0h1O0h1o) from @VictorLamoine.

**Comment by yijiangh** [comment]
should change move_group plan to execution to avoid loop motion display.

**Comment by VictorLamoine** [comment]
FIY the repository containing the example code was migrated here:
https://gitlab.com/InstitutMaupertuis/simple_rviz_plugin
